#!/usr/bin/env python3
"""Generate platform adapters from core skill spec and keep SKILL.md in sync."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE_PATH = ROOT / "core" / "skill-core.md"

BASE_FRONTMATTER = """---
name: critical-debater-suite
description: >
  Multi-agent adversarial debate system with 4 roles (Pro, Con, Judge, Orchestrator),
  per-round evidence refresh, 5-element reasoning chains, and structured bilingual
  Markdown report output. Use this skill when the user says \"debate\", \"start a debate\",
  \"red team this\", \"analyze from multiple perspectives\", or provides a topic for
  critical examination.
license: MIT-0
compatibility: {compatibility}
metadata:
  author: xwxga
  version: \"2.1.0\"
  homepage: \"https://github.com/xwxga/critical-debater\"
  tags: debate, evidence, reasoning, multi-agent, report
---
"""

ROUTING_TABLE = """## Intent → Capability Routing

| User Intent | Route To |
|---|---|
| \"debate\", \"start a debate\", \"red team this\", \"analyze from multiple perspectives\" | `capabilities/debate.md` |
| \"search evidence\", \"build evidence store\" | `capabilities/source-ingest.md` |
| \"check freshness\" | `capabilities/freshness-check.md` |
| \"verify evidence\" | `capabilities/evidence-verify.md` |
| \"build arguments\" | `capabilities/debate-turn.md` |
| \"judge round\", \"audit round\" | `capabilities/judge-audit.md` |
| \"update claims\" | `capabilities/claim-ledger-update.md` |
| \"check analogy\" | `capabilities/analogy-safeguard.md` |
| \"final report\", \"synthesis\" | `capabilities/final-synthesis.md` |
"""

TOOL_TABLE = """## Generic Tool Names

| Generic Name | Claude Code | Codex | GPT/OpenClaw |
|---|---|---|---|
| `search` | WebSearch | web_search | web_search |
| `fetch` | WebFetch | - | browse |
| `spawn_role` | Agent | subprocess | - |
| `read` | Read | read | read |
| `write` | Write | write | write |
"""


def render_header(title: str) -> str:
    return f"""# {title}

## Changelog / 变更日志

| 时间 / Time | 作者 / Author | 变更 / Change |
|---|---|---|
| 2026-03-13 17:40 | Codex | 迁移到 Core+Adapters 生成模式，统一兼容校验 / Move to Core+Adapters generation with unified compatibility checks |

> Generated by `scripts/build-skill-adapters.py`. Do not hand-edit this file.

"""


def render_adapter(target: str, compatibility: str, runtime_notes: str, core_text: str) -> str:
    return (
        BASE_FRONTMATTER.format(compatibility=compatibility)
        + render_header(f"Critical Debater Suite — {target} Adapter")
        + "## Adapter Notes / 适配说明\n\n"
        + runtime_notes
        + "\n\n"
        + ROUTING_TABLE
        + "\n"
        + TOOL_TABLE
        + "\n"
        + "## Core Source / 核心来源\n\n"
        + "The following core spec is the single source of truth:\n"
        + "以下 Core 规范是唯一语义来源：\n\n"
        + core_text
    )


def render_main_skill(core_text: str) -> str:
    compatibility = "Requires bash, jq, python3, shasum, and internet access for web search."
    adapter_refs = """## Adapter Targets / 适配目标

- `adapters/claude-code/SKILL.md`
- `adapters/codex/SKILL.md`
- `adapters/openclaw/SKILL.md`

Top-level `SKILL.md` is kept for backward compatibility and generated from the same core source.
顶层 `SKILL.md` 保持向后兼容，并由同一 Core 生成。

"""
    return (
        BASE_FRONTMATTER.format(compatibility=compatibility)
        + render_header("Critical Debater Suite — Routing")
        + ROUTING_TABLE
        + "\n"
        + TOOL_TABLE
        + "\n"
        + adapter_refs
        + "## Core Source / 核心来源\n\n"
        + core_text
    )


def sync_file(path: Path, content: str, check_only: bool) -> bool:
    if check_only:
        if not path.exists():
            print(f"MISSING: {path}")
            return False
        current = path.read_text(encoding="utf-8")
        if current != content:
            print(f"OUTDATED: {path}")
            return False
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"WROTE: {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate/check skill adapters")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are out-of-date")
    args = parser.parse_args()

    if not CORE_PATH.exists():
        print(f"ERROR: Missing core spec: {CORE_PATH}")
        return 2

    core_text = CORE_PATH.read_text(encoding="utf-8")

    outputs: dict[Path, str] = {
        ROOT / "SKILL.md": render_main_skill(core_text),
        ROOT / "adapters" / "claude-code" / "SKILL.md": render_adapter(
            "Claude Code",
            "Requires Claude Code runtime, bash, jq, python3, and internet access.",
            "- Suggested root: `.claude/skills/critical-debater-suite`\n"
            "- Avoid `../` traversal and symlink escapes\n"
            "- Keep capability routing and completion markers unchanged",
            core_text,
        ),
        ROOT / "adapters" / "codex" / "SKILL.md": render_adapter(
            "Codex",
            "Requires Codex runtime, bash, jq, python3, and internet access.",
            "- Suggested root: `$CODEX_HOME/skills/critical-debater-suite`\n"
            "- Use workspace-safe paths only\n"
            "- Keep capability routing and completion markers unchanged",
            core_text,
        ),
        ROOT / "adapters" / "openclaw" / "SKILL.md": render_adapter(
            "OpenClaw",
            "Requires OpenClaw runtime, bash, jq, python3, and internet access.",
            "- Use configured skill root only\n"
            "- No `../` traversal outside configured root\n"
            "- Keep capability routing and completion markers unchanged",
            core_text,
        ),
    }

    ok = True
    for path, content in outputs.items():
        if not sync_file(path, content, args.check):
            ok = False

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
